_wandb:
    value:
        cli_version: 0.23.1
        e:
            8um6sq90f3hqwsik3a6hv3dzao9jzlm8:
                args:
                    - --batch-size
                    - "32"
                    - --num-epochs
                    - "50"
                    - --output-dir
                    - ./runs/feature_training_20251213_045403
                    - --wandb-project
                    - hierarchical-vlm
                    - --wandb-run-name
                    - feature_training_20251213_045403
                codePath: hierarchicalvlm/train/train_features.py
                codePathLocal: hierarchicalvlm/train/train_features.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1967317549056"
                        used: "1657561026560"
                email: achinda1@student.gsu.edu
                executable: /home/adelechinda/miniconda3/envs/hierarchical_vlm/bin/python3.9
                git:
                    commit: 0df9787810527720e97cb5e2007f8648b81db5d0
                    remote: https://github.com/arrdel/hierarchical-vlm.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 6
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-caa546ac-f4d7-9d9b-26f6-26884f9521d8
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-ff94a989-ef17-a30f-8b77-edac78b8b0f1
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-a87b5a80-c310-7a9f-a20e-6ce199e9029a
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-b0dae5fd-c679-bf40-767f-190356cdfd91
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-8c83d8a6-8e9b-9973-6d37-697d284948ec
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-15d2a194-5120-c84c-86ee-c992b010c196
                host: ai-lab1
                memory:
                    total: "270081527808"
                os: Linux-6.5.0-28-generic-x86_64-with-glibc2.35
                program: /home/adelechinda/home/projects/HierarchicalVLM/hierarchicalvlm/train/train_features.py
                python: CPython 3.9.0
                root: /home/adelechinda/home/projects/HierarchicalVLM
                startedAt: "2025-12-13T09:54:07.885896Z"
                writerId: 8um6sq90f3hqwsik3a6hv3dzao9jzlm8
        m: []
        python_version: 3.9.0
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.9.0
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
annotations_file:
    value: /media/scratch/adele/activitynet/ActivityNet-13/gt.json
batch_size:
    value: 32
feature_dim:
    value: 2048
hidden_dim:
    value: 1024
learning_rate:
    value: 0.0001
log_steps:
    value: 50
num_attention_heads:
    value: 8
num_epochs:
    value: 50
num_layers:
    value: 6
num_workers:
    value: 4
output_dir:
    value: ./runs/feature_training_20251213_045403
seed:
    value: 42
train_feature_dir:
    value: /media/scratch/adele/activitynet/ActivityNet-13/train/train
val_feature_dir:
    value: /media/scratch/adele/activitynet/ActivityNet-13/test/test
weight_decay:
    value: 0.0001
